### ISSUE TITLE
Race condition on connection restart

### ISSUE THREAD

**Issue by smurfix** [agronholm/mqttproto#18]
This can happen when the connection is broken either without a Disconnect packet from the server, or when trio's subtask execution order causes the loop in `_manage_connection` to restart while the disconnect packet is still in the input buffer, unprocessed.

```
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/src/mqttproto/src/mqttproto/async_client.py", line 339, in _manage_connection
      |     await self._do_handshake()
      |   File "/src/mqttproto/src/mqttproto/async_client.py", line 347, in _do_handshake
      |     self._state_machine.connect(
      |   File "/src/mqttproto/src/mqttproto/client_state_machine.py", line 110, in connect
      |     self._out_require_state(MQTTClientState.DISCONNECTED)
      |   File "/src/mqttproto/src/mqttproto/_base_client_state_machine.py", line 188, in _out_require_state
      |     raise MQTTProtocolError(
      | mqttproto.MQTTProtocolError: cannot perform this operation in the CONNECTED state (must be in one of the following states: DISCONNECTED)
```

**Comment by agronholm** [comment]
I guess you're finding out why I haven't released this project to the PyPI yet :smile:

**Comment by smurfix** [comment]
Looks like. Oh well. I'd rather hack on this stuff than continue to wrangle with three layers of PAHO callback legacy.

NB Paho is trivially convertible to sans-io if you squint at it the right way, but that doesn't change the fact that it's a heap of ugly code with *very* slim chances to get that accepted.

**Comment by agronholm** [comment]
For sure. By the time I suspended my work on this, I had only just verified basic pub/sub operation against EMQX which I talked about on the AnyIO Gitter.
